apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: cloudflare
data:
  config.yaml: |
    ingress:
      - hostname: httpbin.aakshranjan.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: longhorn.aakshranjan.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - service: http_status:404
